### ISSUE TITLE
Could not check for invalid players on team

### ISSUE THREAD

**Issue by SuryaRajgor** [Awakened-Redstone/AutoWhitelist#15]
### Version information

autowhitelist-1.1.2

### Expected Behavior

runs normal and get info from roles

### Actual Behavior

got error

### Reproduction Steps

remove all other mods 
remove role ids without member
give bot to admin

### Java version

JAVA 17

### Additional information

[09:09:38] [pool-3-thread-1/ERROR]: Could not check for invalid players on team "YouTube", got "null" when trying to get "net.minecraft.scoreboard.Team" from "YouTube"
com.awakenedredstone.autowhitelist.util.InvalidTeamNameException: Tried to get "net.minecraft.scoreboard.Team" from "YouTube" but got "null".
	at com.awakenedredstone.autowhitelist.AutoWhitelist.lambda$updateWhitelist$5(AutoWhitelist.java:103) ~[autowhitelist-1.1.2.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.awakenedredstone.autowhitelist.AutoWhitelist.updateWhitelist(AutoWhitelist.java:100) ~[autowhitelist-1.1.2.jar:?]
	at com.awakenedredstone.autowhitelist.util.Debugger.analyzeTimings(Debugger.java:15) ~[autowhitelist-1.1.2.jar:?]
	at com.awakenedredstone.autowhitelist.discord.DiscordDataProcessor.updateWhitelist(DiscordDataProcessor.java:75) ~[autowhitelist-1.1.2.jar:?]
	at com.awakenedredstone.autowhitelist.discord.DiscordDataProcessor.run(DiscordDataProcessor.java:25) ~[autowhitelist-1.1.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Awakened-Redstone** [comment]
Have you run `team add YouTube` ?
It isn't being able to find the team
