### ISSUE TITLE
can not implement net.dv8tion.jda.api.interactions.commands.build.CommandData, because it is not an interface 

### ISSUE THREAD

**Issue by meza** [Awakened-Redstone/AutoWhitelist#7]
Hello,

I'm trying to get the mod working with Minecraft 1.18.2 and Fabric Loader 0.13.3 on a server.
This is what I get. Any ideas how to fix?

```
[02:37:21] [AutoWhitelist Bot/ERROR]: Caught previously unhandled exception :
[02:37:21] [AutoWhitelist Bot/ERROR]: AutoWhitelist Bot
java.lang.IncompatibleClassChangeError: class net.dv8tion.jda.api.interactions.commands.build.SlashCommandData can not implement net.dv8tion.jda.api.interactions.commands.build.CommandData, because it is not an interface (net.dv8tion.jda.api.interactions.commands.build.CommandData is in unnamed
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3347) ~[?:?]
	at java.lang.Class.getDeclaredMethods(Class.java:2454) ~[?:?]
	at net.dv8tion.jda.api.hooks.AnnotatedEventManager.updateMethods(AnnotatedEventManager.java:119) ~[me_hypherionmc_sdlink-lib-1.5.1-10902701f056afe9.jar:?]
	at net.dv8tion.jda.api.hooks.AnnotatedEventManager.register(AnnotatedEventManager.java:62) ~[me_hypherionmc_sdlink-lib-1.5.1-10902701f056afe9.jar:?]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.register(EventManagerProxy.java:53) ~[me_hypherionmc_sdlink-lib-1.5.1-10902701f056afe9.jar:?]
	at net.dv8tion.jda.internal.JDAImpl.addEventListener(JDAImpl.java:826) ~[me_hypherionmc_sdlink-lib-1.5.1-10902701f056afe9.jar:?]
	at net.dv8tion.jda.api.JDABuilder.lambda$build$0(JDABuilder.java:1862) ~[me_hypherionmc_sdlink-lib-1.5.1-10902701f056afe9.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1862) ~[me_hypherionmc_sdlink-lib-1.5.1-10902701f056afe9.jar:?]
	at com.awakenedredstone.autowhitelist.discord.Bot.init(Bot.java:105) ~[autowhitelist-1.0.0.jar:?]
	at com.awakenedredstone.autowhitelist.discord.Bot.run(Bot.java:91) ~[autowhitelist-1.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Awakened-Redstone** [comment]
Have you enabled slash commands on the mod?
Ans also, can you inform the steps to reproduce the issue, or if happens on the server start.
Thanks, I'm looking into it, and this information will help to fix the issue faster.

**Comment by meza** [comment]
I have no idea how to enable or to disable the slash commands, there's no documentation (that I've found). I wouldn't need them. All I need is a discord role to be synced with the whitelist

**Comment by meza** [comment]
All I've done is added the mod, added my token and owner ID + one single role ID to the config the mod generates. Nothing else. This happens on server start

**Comment by Awakened-Redstone** [comment]
Ok thanks, I'll try to downgrade the mod to the LTS version of JDA to see if the issue is fixed.

**Comment by Awakened-Redstone** [comment]
Due to some limitation on testing I can't verify it will work on most environments, but this update should fix the issue and hopefully not bring a new one 
https://modrinth.com/mod/autowhitelist/version/1.0.1

**Comment by meza** [comment]
This works, thanks!
